---
# tasks file for roles/iti-webserver-role
- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy custom index
  copy:
    dest: /usr/share/nginx/html/index.html
    content: |
      <h1>Welcome {{ my_name }}</h1>
      <p>Hostname: {{ ansible_hostname }}</p>
      <p>IP: {{ ansible_default_ipv4.address }}</p>
