---
# tasks file for roles/jenkins-role
- name: Install Java (required for Jenkins)
  dnf:
    name: java-11-openjdk
    state: present

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true
